journal/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('journal/', include('journalapp.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

journalapp/urls.py
from django.urls import path,re_path
from .views import *

urlpatterns=[
    path('faculties/',FacultiesListView.as_view(),name='faculties'),
    path('faculties/<int:pk>/',FacultyView,name='Faculty_Detail'),
    path('faculties/groups/',get_group_by_cafedra, name='get_groups_by_cafedra'),
    path('faculties/all_groups/',get_all_groups_in_faculty_in_json, name='get_all_groups_in_faculty'),
    path('all_groups/<int:pk>/', group_view, name='group_view'),
    path('schedules/<int:pk>/',schedule_view,name='schedule'),
    path('journal/<int:jpk>/',journal_view,name='journal_view'),
    path('journal/marks/',get_all_marks_by_enter,name='get_all_marks'),
    path('journal/all_marks/',get_all_marks,name = 'marks')



]

journalapp/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.


class Student(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    student_code = models.CharField(max_length=8, unique=True)
    group = models.ForeignKey('StudentsGroup',on_delete=models.CASCADE)

    def __str__(self):
        return "{0} {1}".format(self.user.first_name, self.user.last_name)


class StudentsGroup(models.Model):
    name_of_group = models.CharField(max_length=7)


    cafedra = models.ForeignKey('Cafedra',on_delete=models.CASCADE)


    def __str__(self):
        return "{0}".format(self.name_of_group)


class Teacher(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    cafedra = models.ForeignKey('Cafedra',on_delete=models.CASCADE)


    def __str__(self):
        return "{0} {1}".format(self.user.first_name,self.user.last_name)

    class Meta:
        permissions=(('can_edit_marks','edit marks'),)


class Cafedra(models.Model):
    name_of_cafedra = models.CharField(max_length=50)
    faculty = models.ForeignKey('Faculty',on_delete=models.CASCADE)

    def __str__(self):
        return self.name_of_cafedra


class Faculty(models.Model):
    name_of_faculty = models.CharField(max_length=60)

    def __str__(self):
        return self.name_of_faculty


class Subject(models.Model):
    name = models.CharField(max_length=200,primary_key=True)

    def __str__(self):
        return self.name


class Lesson(models.Model):
    subjects = models.ForeignKey(Subject,on_delete=models.CASCADE,null=True)
    time = models.TimeField(verbose_name='Time')
    teachers = models.ManyToManyField(Teacher)

    def __str__(self):
        return "{0}".format(self.subjects.name)

    def Days(self):
        days = []
        for i in self.day_set.all():

            days.append(int(i.name_of_day))
        return days



class Day(models.Model):

    choices = (
        ('0','Monday'),
        ('1','Tuesday'),
        ('2','Wednesday'),
        ('3','Thursday'),
        ('4','Friday')
    )
    name_of_day = models.CharField(max_length=15,choices=choices)
    lessons = models.ManyToManyField(Lesson)
    date = models.DateField(null=True)
    schedule = models.ForeignKey('Schedule',on_delete=models.CASCADE)

    def __str__(self):
        return "{0}".format(self.get_name_of_day_display())

class Schedule(models.Model):
    group = models.OneToOneField(StudentsGroup,on_delete=models.CASCADE)

    def __str__(self):
        return "shedule {0}".format(self.group.name_of_group)

class Semestr(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return "{0}-{1}".format(self.start_date,self.end_date)


class Journal(models.Model):
    schedule = models.OneToOneField(Schedule,on_delete=models.CASCADE)
    semestr = models.ForeignKey(Semestr,on_delete=models.CASCADE)
    group = models.OneToOneField(StudentsGroup,on_delete=models.CASCADE)

    def __str__(self):
        return "journal {0}".format(self.group.name_of_group)


class Mark(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE,null=True)

    subject = models.ForeignKey(Subject,on_delete=models.CASCADE,null=True)
    value = models.CharField(max_length=2)
    date = models.DateField()
    rowindex=models.IntegerField()
    colindex=models.IntegerField()

    def __str__(self):
        return "{0} {1}".format(self.date,self.value)

journalapp/views.py
from django.shortcuts import render
from .models import *
from django.views import generic
from django.http import JsonResponse,HttpResponse
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
import datetime
# Create your views here.


class FacultiesListView(generic.ListView):
    model = Faculty
    template_name = 'journalapp/faculties.html'

def FacultyView(request,pk):

    faculty = Faculty.objects.all().get(pk=pk)
    name = faculty.name_of_faculty
    cafedras = faculty.cafedra_set.all()
    print(request)
    return render(request,"journalapp/Faculty_Detail.html",{'name':name,'cafedras':cafedras})


def get_group_by_cafedra(request):

    name_of_cafedra = request.GET.get('name_of_cafedra')


    cafedra = Cafedra.objects.get(name_of_cafedra__exact=name_of_cafedra)
    queryset = serializers.serialize('json',cafedra.studentsgroup_set.all())


    data = {
        'groups': queryset
    }


    return JsonResponse(data, safe=True)

def get_all_groups_in_faculty_in_json(request):

    name_of_faculty = request.GET.get('name_of_faculty')
    faculty = Faculty.objects.get(name_of_faculty=name_of_faculty)

    cafedras = faculty.cafedra_set.all()

    query=[]
    for cafedra in cafedras:
        groups=cafedra.studentsgroup_set.all()
        for i in groups:
            query.append(i)



    queryset = serializers.serialize('json',query)

    data = {
        'groups': queryset
    }

    return JsonResponse(data, safe=True)


def group_view(request,pk):
    group = StudentsGroup.objects.get(pk=pk)

    name = group.name_of_group
    cafedra_name = group.cafedra.name_of_cafedra
    faculty_name = group.cafedra.faculty.name_of_faculty
    students = group.student_set.all()
    schedule = group.schedule
    journal = group.journal


    return render(request,"journalapp/Group_Detail.html",{'name':name,'cafedra_name':cafedra_name,
                                                          'faculty_name':faculty_name,'students':students,
                                                          'schedule':schedule,'journal':journal})


def schedule_view(request,pk):
    schedule = Schedule.objects.get(pk=pk)
    days = schedule.day_set.all()

    return render(request,"journalapp/schedule.html", {'schedule':schedule,'days':days})


@login_required
def journal_view(request,jpk):
    journal = Journal.objects.get(pk=jpk)
    group = journal.group
    students = journal.group.student_set.all()
    semestr = journal.semestr
    startdate = semestr.start_date
    enddate = semestr.end_date
    schedule = journal.schedule
    days = schedule.day_set.all()
    lessons= set()
    dates = []
    for day in days:
        for lesson in day.lessons.all():
            lessons.add(lesson)

    while startdate != enddate:
        if startdate.weekday() != 5 and startdate.weekday() != 6:
            dates.append(startdate)
        startdate += datetime.timedelta(days=1)

    marks=[]
    for st in group.student_set.all():
        for i in st.mark_set.all():
            marks.append(i)

    return render(request,"journalapp/journalview.html",{'dates':dates,'students':students,
                                                         'lessons':lessons,'group':group,'marks':marks})



def get_all_marks_by_enter(request):
    value = request.GET.get('value')
    subject_name = request.GET.get('subject')
    colindex = int(request.GET.get('colindex'))
    rowindex = int(request.GET.get('rowindex'))
    day = int(request.GET.get('day'))
    mounth = int(request.GET.get('mounth'))
    year = int(request.GET.get('year'))
    group_name = request.GET.get('group')
    first_name = request.GET.get('first_name')
    last_name = request.GET.get('last_name')

    group = StudentsGroup.objects.get(name_of_group=group_name)
    schedule = group.schedule
    date = datetime.date(year=year,month=mounth,day=day)


    subject = Subject.objects.get(pk=subject_name)
    student = group.student_set.get(user__first_name=first_name,user__last_name=last_name)
    if value=='' or value==' ':
        Marks = Mark.objects.filter(student=student,date=date,subject=subject)
        for i in Marks.all():
            i.delete()
    else:
        mark,result = Mark.objects.get_or_create(subject=subject,student=student,date=date,colindex=colindex,
                                                 rowindex=rowindex)
        mark.value = value
        mark.save()

    if student.user.email is not None:
        send_mail('Journal','you have a new mark','localhost',[student.user.email])



    students = group.student_set.all()
    marks=[]
    for st in students:
        stmarks = st.mark_set.all()
        for m in stmarks:
            marks.append(m)
    marks = serializers.serialize('json',marks)

    data={
        'marks':marks,
    }
    return JsonResponse(data)



def get_all_marks(request):
    group_name = request.GET.get('group')

    group = StudentsGroup.objects.get(name_of_group=group_name)

    students = group.student_set.all()

    marks =[]

    for st in students:
        stmarks = st.mark_set.all()
        for m in stmarks:
            marks.append(m)
    marks = serializers.serialize('json',marks)

    data={
        'marks': marks,
    }
    return JsonResponse(data)

journalapp/templates/journalapp/Faculty_Detail.html
{% extends 'base.html' %}
{% load static %}
{% block title%}{{ name }}{% endblock %}

{% block content %}
    <h1 class="journal-header" id="Faculty_Name">{{ name }}</h1>
    <h3 class="journal-header"><span>Groups</span></h3>
    <div class="content-list" id="RadioPanel">
        <form id="radioform" method="GET" class="col-sm-3">
        {% csrf_token %}
            <div id="All">
            <input type="Radio" id="All_Cafedras" checked name="Radio" value="all">
            <label for="All_Cafedras">All</label>
            </div>
            <hr>
            {% for cafedra in cafedras %}
                <div>
                <input type="Radio" id="{{ cafedra.name_of_cafedra }}" class="RadioItem"  name="Radio" value="{{ cafedra.name_of_cafedra }}">
                <label for="{{ cafedra.name_of_cafedra }}">{{ cafedra.name_of_cafedra }}</label>
                </div>
            {% endfor %}



        </form>

    </div>
    {% endblock %}
    {% block script %}
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script>
        $(function () {


         $('.RadioItem').change(function () {
             var name_of_cafedra = $('input[name=Radio]:checked').val();

             $.ajax({
                 type:"GET",
                url : '{% url "get_groups_by_cafedra" %}',
                 data :{

                    'name_of_cafedra': name_of_cafedra
                 },



                 dataType: 'json',
                 success : function (data) {
                    $('.cafedra_name').remove();
                   var groups = JSON.parse(data['groups']);
                   for(var i=0;i<groups.length;i++){
                       name_of_group = groups[i].fields['name_of_group'];
                       pk = groups[i].pk;




                       $('.content-list').append(`<p class="cafedra_name"><a href='{% url "group_view" pk=2 %}'>${name_of_group}</a></p>`.replace(2,pk))
                   }


                 }

             })
         });

         function getAllcafedras(){
             var name_of_faculty = $('#Faculty_Name').text();
             $.ajax({
                 type: "GET",
                 url: "{% url 'get_all_groups_in_faculty' %}",
                 data: {
                     'name_of_faculty': name_of_faculty,
                 },
                 dataType: 'json',
                 success: function (data) {
                     $('.cafedra_name').remove();

                     var groups = JSON.parse(data['groups']);

                     for(var i=0;i<groups.length;i++){
                         name_of_group = groups[i].fields['name_of_group'];
                         console.log(typeof(3));
                         pk = groups[i].pk;




                         $('.content-list').append(`<p class="cafedra_name"><a href='{% url "group_view" pk=2%}'>${name_of_group}</a></p>`.replace(2,pk))
                   }

                 }

             })
         }
         $('#All_Cafedras').change(getAllcafedras);

         getAllcafedras();


});
    </script>
{% endblock %}

journalapp/templates/journalapp/Group_Detail.html
{% extends 'base.html' %}
{% block title %}{{ name }}{% endblock %}



{% block content %}
    <h1 class="journal-header"><span>{{ name }}</span></h1>
    <p class="Cafedra_name" style="margin-top: 2rem"><strong>Cafedra:</strong>{{ cafedra_name }}</p>
    <p class="Faculty_name" style="margin-bottom: 0.5rem"><strong>Faculty:</strong><span>{{ faculty_name }}</span></p>
    <p class="schedule" style="margin-bottom: 0.5rem"><a href="{% url 'schedule' pk=schedule.pk %}">Schedule</a></p>
    {% if user.is_authenticated %}
        <p class="journal"><a href="{% url 'journal_view' jpk=journal.pk %}">Journal</a></p>
    {% endif %}
{% endblock %}

journalapp/templates/journalapp/faculties.html
{% extends 'base.html' %}
{% block title %}
    faculties
{% endblock %}

{% block content %}
    <h1 class="journal-header"><span>Faculties</span></h1>
    <ul class="content-list">
    {% for faculty in faculty_list %}
        <li><a href="{% url 'Faculty_Detail' pk=faculty.pk %}">{{ faculty.name_of_faculty }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

journalapp/templates/journalapp/journalview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h1 class="journal-header"><span>{{ group.name_of_group }}</span></h1>
    <span class="left-arrow"><i class="fas fa-angle-left" onclick="changeLeft()"></i></span>
    <span class="rigth-arrow"><i class="fas fa-angle-right" onclick="changeRight()"></i></span>
    <div class="slide-window">

    {% for lesson in lessons %}

    <div class="les-item">
    <h3 class="subject"  id="{{ lesson.subjects.name }}">{{ lesson.subjects.name}}</h3>
    <table class="journal-table" style="border-left: 1px solid black;">
        <tr style="border-top: 1px solid black;">
        <th style="border-right: 1px solid black;">Students</th>

        {% for date in dates %}
            {% if date.weekday in lesson.Days %}
            <td class="date" style="border-right: 1px solid black;">
                <span class="Mounth">{{ date.month }}</span>
                <span class="day">{{ date.day }}</span>
                <span class="year" >{{ date.year }}</span>
            </td>
            {% endif %}
        {% endfor %}
        </tr>
        {% for student in students %}
            <tr style="border-top: 1px solid black;">
                <td class="stname" style="border-right: 1px solid black; border-bottom: 1px solid black">
                    <span>{{ student.user.last_name }} {{ student.user.first_name }}</span>
                </td>
                {% for date in dates %}

                    {% if date.weekday in lesson.Days %}
                        <td style="border-right: 1px solid black;width: 1rem;border-bottom: 1px solid black" class="input">

                        </td>
                    {% endif %}
                {% endfor %}

            </tr>
        {% endfor %}

    </table>
    </div>

    {% endfor %}
    </div>

{% endblock %}
{% block script %}
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'scripts/slider.js' %}"></script>

	<!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script>
        $(function () {
            {% if perms.journalapp.can_edit_marks %}
            $('td.input').click(function (e) {

                var el = e.target||e.srcElement;
                var el_name = el.tagName.toLowerCase();
                if(el_name=='input') {return false;}

                var val = $(this).val();

                var input = `<input type="text" id="edit"  value="${val}"/>`;

                $(this).empty().append(input);

                $('#edit').focus();

                
                $('#edit').blur(function () {

                    var val = $(this).val();

                    $(this).parent().empty().html(val);
                });


            });
             $(window).keydown(function (event) {
                    if(event.keyCode==13){
                        column=$('#edit').parent();
                        row = column.parent();
                        table = row.parent();
                        maindiv =table.parent().parent();

                        subject = maindiv.children()[0].innerHTML;
                        colindex = column.index();
                        rowindex = row.index();


                        day = table.children()[0].cells[colindex].children[1].innerHTML;
                        mounth = table.children()[0].cells[colindex].children[0].innerHTML;
                        year = table.children()[0].cells[colindex].children[2].innerHTML;
                        group = $('h1.journal-header').children()[0].innerHTML;


                        value = $('#edit').val();
                        var regex = /^[0-9]{0,2}$|n/g;
                        if(regex.test(value)==true){
                            stname= table.children()[rowindex].cells[0].children[0].innerHTML;
                            firts_name = stname.split(' ')[1];
                            last_name = stname.split(' ')[0];


                            $.ajax({
                                url: '{% url "get_all_marks" %}',
                                type:'GET',
                                data:{
                                    'value':value,
                                    'subject':subject,
                                    'colindex':colindex,
                                    'rowindex':rowindex,
                                    'day': day,
                                    'mounth':mounth,
                                    'year':year,
                                    'group':group,
                                    'first_name':firts_name,
                                    'last_name':last_name,
                                },
                                dataType:'json',
                                success : function (data) {
                                   get_marks_from_json(data);
                                }
                        });

                                $('#edit').blur();
                        }
                        else{
                            $('#edit').css('color','red');

                        }

                    }

                });
            {% endif %}


             function pageReady() {
                 group = $('h1.journal-header').children()[0].innerHTML;
                 $.ajax({
                     url:'{% url "marks"%}',
                     type:'GET',
                     data:{
                         'group':group,
                     },
                     dataType: 'json',
                     success: function (data) {
                         get_marks_from_json(data);
                     }

                 })

             }


             function get_marks_from_json(data) {
                 var marks = JSON.parse(data['marks']);
                 for(var i=0;i<marks.length;i++){
                     val = marks[i].fields['value'];
                     row_index = marks[i].fields['rowindex'];
                     col_index = marks[i].fields['colindex'];
                     sub_name = marks[i].fields['subject'];

                     tab = $(`#${sub_name}`).next();
                     tbody = tab.children()[0];
                     tbody.children[row_index].cells[col_index].innerHTML = val;
                 }
             }






             pageReady();


        })
    </script>

{% endblock %}

journalapp/templates/journalapp/schedule.html
{% extends 'base.html' %}
{% block title %}schedule of {{ schedule.group.name_of_group }}{% endblock %}

{% block content %}
    <h1 class="journal-header"><span>{{ schedule.group.name_of_group }}</span></h1>
    <ul class="schedule-ul">
        {% for day in days %}
            <li>
                <table>

                    <th class="day">{{ day.get_name_of_day_display }}</th>

                    {% for lesson in day.lessons.all %}
                        <tr>
                            <td>{{ lesson.subjects.name }}</td>
                            <td style="">{{ lesson.time }}</td>
                        </tr>
                    {% endfor %}
                </table>


            </li>
        {% endfor %}
    </ul>
{% endblock %}